# Generated by Django 3.2.5 on 2021-07-20 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210716_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='orderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
