# Generated by Django 3.2.4 on 2021-07-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_orderlist_orderuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='orderProduct',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='productOrder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='orderUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
