# Generated by Django 3.2.4 on 2021-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210726_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
